name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Zip the build artifacts
      run: zip -r build.zip .next node_modules package.json

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Transfer the build to the server
      uses: appleboy/scp-action@v0.1.1
      with:
        source: "build.zip"
        target: "/home/u820803326/domains/webnexa.net/public_html/our_projects/next/nstarter/build.zip"
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/u820803326/domains/webnexa.net/public_html/our_projects/next/nstarter
          echo "Unzipping the build..."
          unzip -o build.zip
          rm build.zip
          echo "Starting the application..."
          npm start
