name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 154.56.33.96
        username: u820803326
        port: 65002
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e # Exit immediately if a command exits with a non-zero status
          cd /home/u820803326/domains/webnexa.net/public_html/our_projects/next/nstarter
          
          echo "Pulling latest code from main branch..."
          git pull origin main

          echo "Removing old build and node_modules..."
          rm -rf .next
          rm -rf node_modules
          
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          echo "Switching to Node.js version 20..."
          nvm use 20

          echo "Installing dependencies..."
          npm ci

          echo "Building the project..."
          npm run build

          echo "Starting the application..."
          npm start
